package enum

// AdvertiserShowStatus 广告账户显示状态。
type AdvertiserShowStatus string

const (
	// SHOW_ACCOUNT_STATUS_NOT_APPROVED 未通过
	SHOW_ACCOUNT_STATUS_NOT_APPROVED AdvertiserShowStatus = "SHOW_ACCOUNT_STATUS_NOT_APPROVED"
	// SHOW_ACCOUNT_STATUS_APPROVED 已通过
	SHOW_ACCOUNT_STATUS_APPROVED AdvertiserShowStatus = "SHOW_ACCOUNT_STATUS_APPROVED"
	// SHOW_ACCOUNT_STATUS_IN_REVIEW 审核中
	SHOW_ACCOUNT_STATUS_IN_REVIEW AdvertiserShowStatus = "SHOW_ACCOUNT_STATUS_IN_REVIEW"
	// SHOW_ACCOUNT_STATUS_PUNISHED 惩罚中
	SHOW_ACCOUNT_STATUS_PUNISHED AdvertiserShowStatus = "SHOW_ACCOUNT_STATUS_PUNISHED"
)
