package enum

// APIServiceType API 产品列表。
type APIServiceType string

const (
	// BUSINESS_CENTER_API：商务中心 API。
	BUSINESS_CENTER_API APIServiceType = "BUSINESS_CENTER_API"
	// CREATIVES_API：创意管理 API。
	CREATIVES_API APIServiceType = "CREATIVES_API"
	// CATALOG_API：商品库 API。
	CATALOG_API APIServiceType = "CATALOG_API"
	// TIKTOK_STORE_API：TikTok Store API。
	TIKTOK_STORE_API APIServiceType = "TIKTOK_STORE_API"
	// CAMPAIGN_API：推广系列管理 API 。
	CAMPAIGN_API APIServiceType = "CAMPAIGN_API"
	// REPORTING_API：报表 API。
	REPORTING_API APIServiceType = "REPORTING_API"
	// AUDIENCE_API：受众 API。
	AUDIENCE_API APIServiceType = "AUDIENCE_API"
	// STREAMING_API：流式 API。
	STREAMING_API APIServiceType = "STREAMING_API"
	// EVENTS_API：事件 API。
	EVENTS_API APIServiceType = "EVENTS_API"
	// ACCOUNTS_API：账号 API。
	ACCOUNTS_API APIServiceType = "ACCOUNTS_API"
	// MENTIONS_API：提及 API。
	MENTIONS_API APIServiceType = "MENTIONS_API"
	// TIKTOK_ONE_API：TikTok One API。
	TIKTOK_ONE_API APIServiceType = "TIKTOK_ONE_API"
	// DISCOVERY_API：热门发现 API。
	DISCOVERY_API APIServiceType = "DISCOVERY_API"
	// SPARK_RECOMMEND_API：Spark Ads 推荐 API。
	SPARK_RECOMMEND_API APIServiceType = "SPARK_RECOMMEND_API"
	// BUSINESS_MESSAGING_API：Business Messaging API。
	BUSINESS_MESSAGING_API APIServiceType = "BUSINESS_MESSAGING_API"
)
