package enum

// BidStrategy 竞价策略。
type BidStrategy string

const (
	// BID_STRATEGY_COST_CAP
	BID_STRATEGY_COST_CAP BidStrategy = "BID_STRATEGY_COST_CAP"
	// BID_STRATEGY_BID_CAP
	BID_STRATEGY_BID_CAP BidStrategy = "BID_STRATEGY_BID_CAP"
	// BID_STRATEGY_MAX_CONVERSION
	BID_STRATEGY_MAX_CONVERSION BidStrategy = "BID_STRATEGY_MAX_CONVERSION"
	// BID_STRATEGY_LOWEST_COST
	BID_STRATEGY_LOWEST_COST BidStrategy = "BID_STRATEGY_LOWEST_COST"
)
