package enum

// SecondaryStatus 二级状态
type SecondaryStatus string

const (
	// 推广系列状态
	// CAMPAIGN_STATUS_DELETE 已删除
	CAMPAIGN_STATUS_DELETE SecondaryStatus = "CAMPAIGN_STATUS_DELETE"
	// CAMPAIGN_STATUS_ADVERTISER_AUDIT_DENY 广告主审核未通过
	CAMPAIGN_STATUS_ADVERTISER_AUDIT_DENY SecondaryStatus = "CAMPAIGN_STATUS_ADVERTISER_AUDIT_DENY"
	// CAMPAIGN_STATUS_ADVERTISER_AUDIT 广告主审核中
	CAMPAIGN_STATUS_ADVERTISER_AUDIT SecondaryStatus = "CAMPAIGN_STATUS_ADVERTISER_AUDIT"
	// ADVERTISER_CONTRACT_PENDING 广告主合同未生效
	ADVERTISER_CONTRACT_PENDING SecondaryStatus = "ADVERTISER_CONTRACT_PENDING"
	// ADVERTISER_ACCOUNT_PUNISH 广告主账号被惩罚
	ADVERTISER_ACCOUNT_PUNISH SecondaryStatus = "ADVERTISER_ACCOUNT_PUNISH"
	// CAMPAIGN_STATUS_BUDGET_EXCEED 超出预算
	CAMPAIGN_STATUS_BUDGET_EXCEED SecondaryStatus = "CAMPAIGN_STATUS_BUDGET_EXCEED"
	// CAMPAIGN_STATUS_DISABLE 暂停
	CAMPAIGN_STATUS_DISABLE SecondaryStatus = "CAMPAIGN_STATUS_DISABLE"
	// CAMPAIGN_STATUS_AWAITING_RELEASE 等待释放。 该 SKAN 4.0 推广系列正在回传数据。为确保报表数据准确性，建议您等待数日，数日后本推广系列的配额将释放。
	CAMPAIGN_STATUS_AWAITING_RELEASE SecondaryStatus = "CAMPAIGN_STATUS_AWAITING_RELEASE"
	// CAMPAIGN_STATUS_IDENTITY_USED_BY_GMV_MAX_AD 您想用在该推广系列内某个广告中的认证身份（发布身份）不可用，因为该身份已被另一优化目标为最大成交额（optimization_goal SecondaryStatus =GMV）的广告使用。
	CAMPAIGN_STATUS_IDENTITY_USED_BY_GMV_MAX_AD SecondaryStatus = "CAMPAIGN_STATUS_IDENTITY_USED_BY_GMV_MAX_AD"
	// CAMPAIGN_STATUS_ENABLE 投放中
	CAMPAIGN_STATUS_ENABLE SecondaryStatus = "CAMPAIGN_STATUS_ENABLE"
	// CAMPAIGN_STATUS_ALL 所有包含已删除
	CAMPAIGN_STATUS_ALL SecondaryStatus = "CAMPAIGN_STATUS_ALL"
	// CAMPAIGN_STATUS_NOT_DELETE 所有不含已删除
	CAMPAIGN_STATUS_NOT_DELETE SecondaryStatus = "CAMPAIGN_STATUS_NOT_DELETE"
	// CAMPAIGN_STATUS_TTS_TT_ASSET_UNAVAILABLE 您的推广系列中使用的素材不可用。请检查推广系列设置。
	CAMPAIGN_STATUS_TTS_TT_ASSET_UNAVAILABLE SecondaryStatus = "CAMPAIGN_STATUS_TTS_TT_ASSET_UNAVAILABLE"
	// CAMPAIGN_STATUS_TTS_TT_IDENTITY_UNAVAILABLE TikTok 账号不可用，请尝试重新关联或选择其他账号创建广告。
	CAMPAIGN_STATUS_TTS_TT_IDENTITY_UNAVAILABLE SecondaryStatus = "CAMPAIGN_STATUS_TTS_TT_IDENTITY_UNAVAILABLE"
	// CAMPAIGN_STATUS_TIKTOK_SHOP_UNAVAILABLE 商店已与商务中心账户取消关联。请重新关联商店。
	CAMPAIGN_STATUS_TIKTOK_SHOP_UNAVAILABLE SecondaryStatus = "CAMPAIGN_STATUS_TIKTOK_SHOP_UNAVAILABLE"
	// CAMPAIGN_STATUS_REVIEW_DISAPPROVED 审核失败
	CAMPAIGN_STATUS_REVIEW_DISAPPROVED SecondaryStatus = "CAMPAIGN_STATUS_REVIEW_DISAPPROVED"
	// CAMPAIGN_STATUS_AD_UNAVAILABLE 整个推广系列已暂停投放，原因是一个或多个广告组被拒或部分素材不可用。
	CAMPAIGN_STATUS_AD_UNAVAILABLE SecondaryStatus = "CAMPAIGN_STATUS_AD_UNAVAILABLE"
	// CAMPAIGN_STATUS_PRODUCT_UNAVAILABLE 推广系列创建后，所选商品不可用。请前往商家中心管理或添加商品。
	CAMPAIGN_STATUS_PRODUCT_UNAVAILABLE SecondaryStatus = "CAMPAIGN_STATUS_PRODUCT_UNAVAILABLE"
	// CAMPAIGN_STATUS_LIVE_GMV_MAX_AUTHORIZATION_CANCEL 由于所选官方 TikTok 账号已将 GMV Max 专属授权授予其他广告账号，此推广系列已暂停。
	CAMPAIGN_STATUS_LIVE_GMV_MAX_AUTHORIZATION_CANCEL SecondaryStatus = "CAMPAIGN_STATUS_LIVE_GMV_MAX_AUTHORIZATION_CANCEL"
	// CAMPAIGN_STATUS_PRODUCT_GMV_MAX_AUTHORIZATION_CANCEL 由于 TikTok Shop 已将 GMV Max 专属授权授予其他广告账号，此推广系列已暂停。
	CAMPAIGN_STATUS_PRODUCT_GMV_MAX_AUTHORIZATION_CANCEL SecondaryStatus = "CAMPAIGN_STATUS_PRODUCT_GMV_MAX_AUTHORIZATION_CANCEL"
	// CAMPAIGN_STATUS_IDENTITY_USED_BY_LIVE_GMV_MAX 由于存在使用此 TikTok 账号创建的投放中的直播 GMV Max 推广系列，此推广系列已暂停。
	CAMPAIGN_STATUS_IDENTITY_USED_BY_LIVE_GMV_MAX SecondaryStatus = "CAMPAIGN_STATUS_IDENTITY_USED_BY_LIVE_GMV_MAX"
	// CAMPAIGN_STATUS_PRODUCT_USED_BY_PRODUCT_GMV_MAX 由于存在为此商店创建的投放中的商品 GMV Max 推广系列，此推广系列已暂停。
	CAMPAIGN_STATUS_PRODUCT_USED_BY_PRODUCT_GMV_MAX SecondaryStatus = "CAMPAIGN_STATUS_PRODUCT_USED_BY_PRODUCT_GMV_MAX"
	// ADGROUP_STATUS_ALL 所有包含已删除
	ADGROUP_STATUS_ALL SecondaryStatus = "ADGROUP_STATUS_ALL"
	// ADGROUP_STATUS_NOT_DELETE 所有不含已删除
	ADGROUP_STATUS_NOT_DELETE SecondaryStatus = "ADGROUP_STATUS_NOT_DELETE"
	// ADGROUP_STATUS_DELETE 已删除
	ADGROUP_STATUS_DELETE SecondaryStatus = "ADGROUP_STATUS_DELETE"
	// ADGROUP_STATUS_CAMPAIGN_DELETE 推广系列删除
	ADGROUP_STATUS_CAMPAIGN_DELETE SecondaryStatus = "ADGROUP_STATUS_CAMPAIGN_DELETE"
	// ADGROUP_STATUS_ADVERTISER_AUDIT_DENY 广告主审核未通过
	ADGROUP_STATUS_ADVERTISER_AUDIT_DENY SecondaryStatus = "ADGROUP_STATUS_ADVERTISER_AUDIT_DENY"
	// ADGROUP_STATUS_ADVERTISER_AUDIT 广告主审核中
	ADGROUP_STATUS_ADVERTISER_AUDIT SecondaryStatus = "ADGROUP_STATUS_ADVERTISER_AUDIT"
	// ADVERTISER_CONTRACT_PENDING 广告主合同未生效
	// ADVERTISER_CONTRACT_PENDING SecondaryStatus = "ADVERTISER_CONTRACT_PENDING"
	// ADVERTISER_ACCOUNT_PUNISH 广告主账号被惩罚
	// ADVERTISER_ACCOUNT_PUNISH SecondaryStatus = "ADVERTISER_ACCOUNT_PUNISH"
	// ADGROUP_STATUS_CAMPAIGN_EXCEED 推广系列超出预算
	ADGROUP_STATUS_CAMPAIGN_EXCEED SecondaryStatus = "ADGROUP_STATUS_CAMPAIGN_EXCEED"
	// ADGROUP_STATUS_BUDGET_EXCEED 广告组超出预算
	ADGROUP_STATUS_BUDGET_EXCEED SecondaryStatus = "ADGROUP_STATUS_BUDGET_EXCEED"
	// ADGROUP_STATUS_BALANCE_EXCEED 广告主余额不足
	ADGROUP_STATUS_BALANCE_EXCEED SecondaryStatus = "ADGROUP_STATUS_BALANCE_EXCEED"
	// ADGROUP_STATUS_ADGROUP_PRE_ONLINE 广告组处于预上线状态，尚未开始投放。
	ADGROUP_STATUS_ADGROUP_PRE_ONLINE SecondaryStatus = "ADGROUP_STATUS_ADGROUP_PRE_ONLINE"
	// ADGROUP_STATUS_AUDIT_DENY 广告组审核拒绝
	ADGROUP_STATUS_AUDIT_DENY SecondaryStatus = "ADGROUP_STATUS_AUDIT_DENY"
	// ADGROUP_STATUS_REAUDIT 修改审核
	ADGROUP_STATUS_REAUDIT SecondaryStatus = "ADGROUP_STATUS_REAUDIT"
	// ADGROUP_STATUS_AUDIT 新建审核
	ADGROUP_STATUS_AUDIT SecondaryStatus = "ADGROUP_STATUS_AUDIT"
	// ADGROUP_STATUS_CREATE 计划新建
	ADGROUP_STATUS_CREATE SecondaryStatus = "ADGROUP_STATUS_CREATE"
	// ADGROUP_STATUS_FROZEN 广告组被冻结
	ADGROUP_STATUS_FROZEN SecondaryStatus = "ADGROUP_STATUS_FROZEN"
	// ADGROUP_STATUS_NOT_START 未到投放时间
	ADGROUP_STATUS_NOT_START SecondaryStatus = "ADGROUP_STATUS_NOT_START"
	// ADGROUP_STATUS_LIVE_NOT_START 已到投放时间但直播未开始。该状态为竞价广告组状态。
	ADGROUP_STATUS_LIVE_NOT_START SecondaryStatus = "ADGROUP_STATUS_LIVE_NOT_START"
	// ADGROUP_STATUS_CAMPAIGN_DISABLE 推广系列暂停
	ADGROUP_STATUS_CAMPAIGN_DISABLE SecondaryStatus = "ADGROUP_STATUS_CAMPAIGN_DISABLE"
	// ADGROUP_STATUS_DISABLE 暂停
	ADGROUP_STATUS_DISABLE SecondaryStatus = "ADGROUP_STATUS_DISABLE"
	// ADGROUP_STATUS_SHADOW_ADGROUP_REAUDIT 重新审核中
	ADGROUP_STATUS_SHADOW_ADGROUP_REAUDIT SecondaryStatus = "ADGROUP_STATUS_SHADOW_ADGROUP_REAUDIT"
	// ADGROUP_STATUS_PIXEL_UNBIND 广告组绑定的Pixel已解绑
	ADGROUP_STATUS_PIXEL_UNBIND SecondaryStatus = "ADGROUP_STATUS_PIXEL_UNBIND"
	// ADGROUP_STATUS_PARTIAL_AUDIT_NO_DELIVERY 广告组部分审核中，且不在投放中
	ADGROUP_STATUS_PARTIAL_AUDIT_NO_DELIVERY SecondaryStatus = "ADGROUP_STATUS_PARTIAL_AUDIT_NO_DELIVERY"
	// ADGROUP_STATUS_PARTIAL_AUDIT_DELIVERY_OK 广告组部分审核中，且在投放中
	ADGROUP_STATUS_PARTIAL_AUDIT_DELIVERY_OK SecondaryStatus = "ADGROUP_STATUS_PARTIAL_AUDIT_DELIVERY_OK"
	// ADGROUP_STATUS_INDUSTRY_QUALIFICATION_MISSING 待补充行业资质
	ADGROUP_STATUS_INDUSTRY_QUALIFICATION_MISSING SecondaryStatus = "ADGROUP_STATUS_INDUSTRY_QUALIFICATION_MISSING"
	// ADGROUP_STATUS_INDUSTRY_QUALIFICATION_EXPIRED 行业资质已过期
	ADGROUP_STATUS_INDUSTRY_QUALIFICATION_EXPIRED SecondaryStatus = "ADGROUP_STATUS_INDUSTRY_QUALIFICATION_EXPIRED"
	// ADGROUP_STATUS_INDUSTRY_QUALIFICATION_DENY 行业资质不通过
	ADGROUP_STATUS_INDUSTRY_QUALIFICATION_DENY SecondaryStatus = "ADGROUP_STATUS_INDUSTRY_QUALIFICATION_DENY"
	// ADGROUP_STATUS_ASSET_AUTHORIZATION_LOST 广告组资产无授权。注意：本状态不可用于筛选广告组。
	ADGROUP_STATUS_ASSET_AUTHORIZATION_LOST SecondaryStatus = "ADGROUP_STATUS_ASSET_AUTHORIZATION_LOST"
	// ADGROUP_STATUS_TRANSCODING_FAIL 广告组视频转码失败。注意：本状态不可用于筛选广告组。
	ADGROUP_STATUS_TRANSCODING_FAIL SecondaryStatus = "ADGROUP_STATUS_TRANSCODING_FAIL"
	// ADGROUP_STATUS_ADGROUP_QUOTA_LIMIT 广告账户下无空余广告组投放配额。如欲新建在投状态的广告组，需先暂停或删除处于“投放中”或“审核中“状态的广告组。注意：本状态不可用于筛选广告组。
	ADGROUP_STATUS_ADGROUP_QUOTA_LIMIT SecondaryStatus = "ADGROUP_STATUS_ADGROUP_QUOTA_LIMIT"
	// ADGROUP_STATUS_IDENTITY_USED_BY_GMV_MAX_AD 您想用在该广告组内某个广告中的认证身份（发布身份）不可用，因为该身份已被另一优化目标为最大成交额（optimization_goal SecondaryStatus =GMV）的广告使用。
	ADGROUP_STATUS_IDENTITY_USED_BY_GMV_MAX_AD SecondaryStatus = "ADGROUP_STATUS_IDENTITY_USED_BY_GMV_MAX_AD"
	// ADGROUP_STATUS_SEARCH_KEYWORDS_IN_REVIEW 该搜索推广系列中的广告组的所有关键词均在审核中。
	ADGROUP_STATUS_SEARCH_KEYWORDS_IN_REVIEW SecondaryStatus = "ADGROUP_STATUS_SEARCH_KEYWORDS_IN_REVIEW"
	// ADGROUP_STATUS_SEARCH_KEYWORDS_NOT_AVAILABLE 该搜索推广系列中的广告组的所有关键词均未通过审核，或未设置关键词。
	ADGROUP_STATUS_SEARCH_KEYWORDS_NOT_AVAILABLE SecondaryStatus = "ADGROUP_STATUS_SEARCH_KEYWORDS_NOT_AVAILABLE"
	// ADGROUP_STATUS_SEARCH_KEYWORDS_PARTIAL_APPROVED 该搜索推广系列中的广告组的部分关键词通过审核，其他关键词仍在审核中或未通过审核。
	ADGROUP_STATUS_SEARCH_KEYWORDS_PARTIAL_APPROVED SecondaryStatus = "ADGROUP_STATUS_SEARCH_KEYWORDS_PARTIAL_APPROVED"
	// ADGROUP_STATUS_DELIVERY_OK 投放中
	ADGROUP_STATUS_DELIVERY_OK SecondaryStatus = "ADGROUP_STATUS_DELIVERY_OK"
	// ADGROUP_STATUS_REVIEW_PARTIALLY_APPROVED 部分广告未通过审核
	ADGROUP_STATUS_REVIEW_PARTIALLY_APPROVED SecondaryStatus = "ADGROUP_STATUS_REVIEW_PARTIALLY_APPROVED"
	// ADGROUP_STATUS_TIME_DONE 已完成,注意：本状态代表该广告组在所设置的投放结束时间结束投放。
	ADGROUP_STATUS_TIME_DONE SecondaryStatus = "ADGROUP_STATUS_TIME_DONE"
	// ADGROUP_STATUS_RF_DEDUCTION_FAILED 预扣费失败
	ADGROUP_STATUS_RF_DEDUCTION_FAILED SecondaryStatus = "ADGROUP_STATUS_RF_DEDUCTION_FAILED"
	// ADGROUP_STATUS_RF_NO_VALID_CREATIVE 无有效创意
	ADGROUP_STATUS_RF_NO_VALID_CREATIVE SecondaryStatus = "ADGROUP_STATUS_RF_NO_VALID_CREATIVE"
	// ADGROUP_STATUS_RF_CLOSED_OTHERS 广告组已关闭
	ADGROUP_STATUS_RF_CLOSED_OTHERS SecondaryStatus = "ADGROUP_STATUS_RF_CLOSED_OTHERS"
	// ADGROUP_STATUS_RF_SHORT_BALANCE 账户余额不足扣款
	ADGROUP_STATUS_RF_SHORT_BALANCE SecondaryStatus = "ADGROUP_STATUS_RF_SHORT_BALANCE"
	// ADGROUP_STATUS_RF_BOOKING 预算/库存已预定
	ADGROUP_STATUS_RF_BOOKING SecondaryStatus = "ADGROUP_STATUS_RF_BOOKING"
	// ADGROUP_STATUS_RF_NO_DELIVERY_CREATIVE 无创意可投
	ADGROUP_STATUS_RF_NO_DELIVERY_CREATIVE SecondaryStatus = "ADGROUP_STATUS_RF_NO_DELIVERY_CREATIVE"
	// ADGROUP_STATUS_RF_SCHEDULE 已排期
	ADGROUP_STATUS_RF_SCHEDULE SecondaryStatus = "ADGROUP_STATUS_RF_SCHEDULE"
	// ADGROUP_STATUS_RF_TERMINATE 广告组已终止
	ADGROUP_STATUS_RF_TERMINATE SecondaryStatus = "ADGROUP_STATUS_RF_TERMINATE"
	// ADGROUP_STATUS_RF_AD_AUDIT_DENY 覆盖和频次广告创意审核未通过
	ADGROUP_STATUS_RF_AD_AUDIT_DENY SecondaryStatus = "ADGROUP_STATUS_RF_AD_AUDIT_DENY"
	// ADVERTISER_ACCOUNT_INVALID 广告账户无效
	ADVERTISER_ACCOUNT_INVALID SecondaryStatus = "ADVERTISER_ACCOUNT_INVALID"
	// ADGROUP_STATUS_RF_ADGROUP_INVALID 覆盖和频次广告组不存在或为其他异常状态
	ADGROUP_STATUS_RF_ADGROUP_INVALID SecondaryStatus = "ADGROUP_STATUS_RF_ADGROUP_INVALID"
	// ADGROUP_STATUS_RF_WITHDRAW_ORDER 覆盖和频次推广已撤单
	ADGROUP_STATUS_RF_WITHDRAW_ORDER SecondaryStatus = "ADGROUP_STATUS_RF_WITHDRAW_ORDER"
	// ADGROUP_STATUS_RF_TIME_DONE 覆盖和频次广告组已完成 注意：本状态代表该覆盖和频次广告组由于预算不足或账户余额不足，在所设置的投放结束时间前结束了投放。
	ADGROUP_STATUS_RF_TIME_DONE SecondaryStatus = "ADGROUP_STATUS_RF_TIME_DONE"
	// ADGROUP_STATUS_PROMOTE_AD_NOT_APPROVED 内容加热广告组中的一个或多个创意未通过审核
	ADGROUP_STATUS_PROMOTE_AD_NOT_APPROVED SecondaryStatus = "ADGROUP_STATUS_PROMOTE_AD_NOT_APPROVED"
	// ADGROUP_STATUS_PROMOTE_WITHDRAW_ORDER 内容加热订单已撤销
	ADGROUP_STATUS_PROMOTE_WITHDRAW_ORDER SecondaryStatus = "ADGROUP_STATUS_PROMOTE_WITHDRAW_ORDER"
	// AD_STATUS_ALL 所有包含已删除
	AD_STATUS_ALL SecondaryStatus = "AD_STATUS_ALL"
	// AD_STATUS_NOT_DELETE 所有不含已删除
	AD_STATUS_NOT_DELETE SecondaryStatus = "AD_STATUS_NOT_DELETE"
	// AD_STATUS_CAMPAIGN_DELETE 推广系列已删除
	AD_STATUS_CAMPAIGN_DELETE SecondaryStatus = "AD_STATUS_CAMPAIGN_DELETE"
	// AD_STATUS_ADGROUP_DELETE 广告组已删除
	AD_STATUS_ADGROUP_DELETE SecondaryStatus = "AD_STATUS_ADGROUP_DELETE"
	// AD_STATUS_DELETE 已删除
	AD_STATUS_DELETE SecondaryStatus = "AD_STATUS_DELETE"
	// AD_STATUS_ADVERTISER_AUDIT_DENY 账号审核拒绝
	AD_STATUS_ADVERTISER_AUDIT_DENY SecondaryStatus = "AD_STATUS_ADVERTISER_AUDIT_DENY"
	// AD_STATUS_ADVERTISER_AUDIT 账号审核中
	AD_STATUS_ADVERTISER_AUDIT SecondaryStatus = "AD_STATUS_ADVERTISER_AUDIT"
	// ADVERTISER_CONTRACT_PENDING 广告主合同未生效
	// ADVERTISER_CONTRACT_PENDING SecondaryStatus = "ADVERTISER_CONTRACT_PENDING"
	// ADVERTISER_ACCOUNT_PUNISH 广告主账号被惩罚
	// ADVERTISER_ACCOUNT_PUNISH SecondaryStatus = "ADVERTISER_ACCOUNT_PUNISH"
	// AD_STATUS_BALANCE_EXCEED 广告账号余额不足
	AD_STATUS_BALANCE_EXCEED SecondaryStatus = "AD_STATUS_BALANCE_EXCEED"
	// AD_STATUS_CAMPAIGN_EXCEED 推广系列超出预算
	AD_STATUS_CAMPAIGN_EXCEED SecondaryStatus = "AD_STATUS_CAMPAIGN_EXCEED"
	// AD_STATUS_BUDGET_EXCEED 广告组超出预算
	AD_STATUS_BUDGET_EXCEED SecondaryStatus = "AD_STATUS_BUDGET_EXCEED"
	// AD_STATUS_AD_PRE_ONLINE 广告处于预上线状态，尚未开始投放。
	AD_STATUS_AD_PRE_ONLINE SecondaryStatus = "AD_STATUS_AD_PRE_ONLINE"
	// AD_STATUS_AUDIT 审核中
	AD_STATUS_AUDIT SecondaryStatus = "AD_STATUS_AUDIT"
	// AD_STATUS_REAUDIT 修改审核中
	AD_STATUS_REAUDIT SecondaryStatus = "AD_STATUS_REAUDIT"
	// AD_STATUS_AUDIT_DENY 审核拒绝
	AD_STATUS_AUDIT_DENY SecondaryStatus = "AD_STATUS_AUDIT_DENY"
	// AD_STATUS_ADGROUP_AUDIT_DENY 广告组审核拒绝
	AD_STATUS_ADGROUP_AUDIT_DENY SecondaryStatus = "AD_STATUS_ADGROUP_AUDIT_DENY"
	// AD_STATUS_ADGROUP_PARTIAL_AUDIT_NO_DELIVERY 广告组部分审核中，且不在投放中
	AD_STATUS_ADGROUP_PARTIAL_AUDIT_NO_DELIVERY SecondaryStatus = "AD_STATUS_ADGROUP_PARTIAL_AUDIT_NO_DELIVERY"
	// AD_STATUS_REVIEW_PARTIALLY_APPROVED 当前广告创意存在拒审情况
	AD_STATUS_REVIEW_PARTIALLY_APPROVED SecondaryStatus = "AD_STATUS_REVIEW_PARTIALLY_APPROVED"
	// AD_STATUS_PARTIAL_AUDIT_DELIVERY_OK 广告部分审核中，且在投放中
	AD_STATUS_PARTIAL_AUDIT_DELIVERY_OK SecondaryStatus = "AD_STATUS_PARTIAL_AUDIT_DELIVERY_OK"
	// AD_STATUS_PARTIAL_AUDIT_NO_DELIVERY 广告部分审核中，且不在投放中
	AD_STATUS_PARTIAL_AUDIT_NO_DELIVERY SecondaryStatus = "AD_STATUS_PARTIAL_AUDIT_NO_DELIVERY"
	// AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_MISSING 待补充行业资质
	AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_MISSING SecondaryStatus = "AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_MISSING"
	// AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_EXPIRED 行业资质已过期
	AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_EXPIRED SecondaryStatus = "AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_EXPIRED"
	// AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_DENY 行业资质不通过
	AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_DENY SecondaryStatus = "AD_STATUS_ADGROUP_INDUSTRY_QUALIFICATION_DENY"
	// AD_STATUS_MUSIC_AUTHORIZATION_MISSING 待补充音乐资质
	AD_STATUS_MUSIC_AUTHORIZATION_MISSING SecondaryStatus = "AD_STATUS_MUSIC_AUTHORIZATION_MISSING"
	// AD_STAUS_PIXEL_UNBIND 广告绑定的Pixel已解绑
	AD_STAUS_PIXEL_UNBIND SecondaryStatus = "AD_STAUS_PIXEL_UNBIND"
	// AD_STATUS_LIVE_OFFLINE 直播未开始
	AD_STATUS_LIVE_OFFLINE SecondaryStatus = "AD_STATUS_LIVE_OFFLINE"
	// AD_STATUS_NOT_START 未到投放时间
	AD_STATUS_NOT_START SecondaryStatus = "AD_STATUS_NOT_START"
	// AD_STATUS_DONE 已完成
	AD_STATUS_DONE SecondaryStatus = "AD_STATUS_DONE"
	// AD_STATUS_CAMPAIGN_DISABLE 推广系列暂停
	AD_STATUS_CAMPAIGN_DISABLE SecondaryStatus = "AD_STATUS_CAMPAIGN_DISABLE"
	// AD_STATUS_ADGROUP_DISABLE 广告组暂停
	AD_STATUS_ADGROUP_DISABLE SecondaryStatus = "AD_STATUS_ADGROUP_DISABLE"
	// ADGROUP_STATUS_FROZEN 广告组被冻结
	// ADGROUP_STATUS_FROZEN SecondaryStatus = "ADGROUP_STATUS_FROZEN"
	// AD_STATUS_DISABLE 广告暂停
	AD_STATUS_DISABLE SecondaryStatus = "AD_STATUS_DISABLE"
	// AD_STATUS_DELIVERY_OK 投放中
	AD_STATUS_DELIVERY_OK SecondaryStatus = "AD_STATUS_DELIVERY_OK"
	// AD_STATUS_PROCESS_AUDIO 抽声进行中 注意：若二级状态长时间显示为 AD_STATUS_PROCESS_AUDIO （前端状态提示“音频处理中，如果此状态持续时间过长，请重新上传素材。”） , 请上传带音频的新视频进行重试。
	AD_STATUS_PROCESS_AUDIO SecondaryStatus = "AD_STATUS_PROCESS_AUDIO"
	// AD_STATUS_TRANSCODING_FAIL 广告视频转码失败。注意：本状态不可用于筛选广告。
	AD_STATUS_TRANSCODING_FAIL SecondaryStatus = "AD_STATUS_TRANSCODING_FAIL"
	// AD_STATUS_ADGROUP_ASSET_AUTHORIZATION_LOST 广告组资产无授权。 注意：本状态不可用于筛选广告。
	AD_STATUS_ADGROUP_ASSET_AUTHORIZATION_LOST SecondaryStatus = "AD_STATUS_ADGROUP_ASSET_AUTHORIZATION_LOST"
	// AD_STATUS_ASSET_AUTHORIZATION_LOST 广告资产无授权。 注意：本状态不可用于筛选广告。
	AD_STATUS_ASSET_AUTHORIZATION_LOST SecondaryStatus = "AD_STATUS_ASSET_AUTHORIZATION_LOST"
	// AD_STATUS_AD_QUOTA_LIMIT 广告对应的广告组因广告账户下无空余广告组投放配额而暂停。 如欲新建在投状态的广告，需先暂停或删除处于“投放中”或“审核中“状态的广告组，然后在新建的广告组下创建广告。 注意：本状态不可用于筛选广告。
	AD_STATUS_AD_QUOTA_LIMIT SecondaryStatus = "AD_STATUS_AD_QUOTA_LIMIT"
	// AD_STATUS_PRODUCT_UNAVAILABLE 您想用在该广告中的商品不可用
	AD_STATUS_PRODUCT_UNAVAILABLE SecondaryStatus = "AD_STATUS_PRODUCT_UNAVAILABLE"
	// AD_STATUS_ANCHOR_UNAVAILABLE 您想用在该广告中的商品链接不可用
	AD_STATUS_ANCHOR_UNAVAILABLE SecondaryStatus = "AD_STATUS_ANCHOR_UNAVAILABLE"
	// AD_STATUS_NO_AUTHORIZATION_OF_SHOWCASE 与您想用在该广告中的橱窗绑定的认证身份（ 发布身份）不可用
	AD_STATUS_NO_AUTHORIZATION_OF_SHOWCASE SecondaryStatus = "AD_STATUS_NO_AUTHORIZATION_OF_SHOWCASE"
	// AD_STATUS_RF_ADGROUP_CLOSED 覆盖和频次广告组已关闭
	AD_STATUS_RF_ADGROUP_CLOSED SecondaryStatus = "AD_STATUS_RF_ADGROUP_CLOSED"
	// AD_STATUS_PROMOTE_AD_OFFLINE_AUDIT 内容加热广告中的一个或多个创意未通过审核
	AD_STATUS_PROMOTE_AD_OFFLINE_AUDIT SecondaryStatus = "AD_STATUS_PROMOTE_AD_OFFLINE_AUDIT"
	// AD_STATUS_PROMOTE_ADGROUP_CLOSED 内容加热广告组已关闭
	AD_STATUS_PROMOTE_ADGROUP_CLOSED SecondaryStatus = "AD_STATUS_PROMOTE_ADGROUP_CLOSED"
)
