package gmvmax

import (
	"context"

	"github.com/bububa/tiktok-business/core"
	"github.com/bububa/tiktok-business/model/campaign/gmvmax"
)

// CustomAnchorVideoListCreate Create shop-level customized TikTok posts
// Use this endpoint to create shop-level customized TikTok posts.
// Shop-level customized TikTok posts are generated by directly linking your TikTok videos to a product at the TikTok Shop level. If the linked product is part of an active campaign, the video linked to that product will be automatically added to that campaign.
func CustomAnchorVideoListCreate(ctx context.Context, clt *core.SDKClient, req *gmvmax.CustomAnchorVideoListCreateRequest, accessToken string) ([]gmvmax.CustomAnchorVideoListCreateError, error) {
	var resp gmvmax.CustomAnchorVideoListCreateResponse
	if err := clt.Post(ctx, "v1.3/gmv_max/creation/custom_anchor_video_list/create/", req, &resp, accessToken); err != nil {
		return nil, err
	}
	return resp.Data.FailureList, nil
}
