package gmvmax

import (
	"context"

	"github.com/bububa/tiktok-business/core"
	"github.com/bububa/tiktok-business/model/campaign/gmvmax"
)

// CustomAnchorVideoListDelete Delete shop-level customized TikTok posts
// Use this endpoint to delete shop-level or campaign-level customized TikTok posts.
// Shop-level customized TikTok posts are generated by directly linking your TikTok videos to a product at the TikTok Shop level. If the linked product is part of an active campaign, the video linked to that product will be automatically added to that campaign. In contrast, campaign-level customized TikTok posts are generated by linking your TikTok videos to a product during the Product GMV Max Campaign creation process and are exclusive to the campaign.
func CustomAnchorVideoListDelete(ctx context.Context, clt *core.SDKClient, req *gmvmax.CustomAnchorVideoListDeleteRequest, accessToken string) error {
	return clt.Post(ctx, "v1.3/gmv_max/creation/custom_anchor_video_list/delete/", req, nil, accessToken)
}
