package gmvmax

import (
	"context"

	"github.com/bububa/tiktok-business/core"
	"github.com/bububa/tiktok-business/model/campaign/gmvmax"
)

// ShopVideoVideoAnchors Get product linkage details of videos in customized posts
// Use this endpoint to retrieve the shop-level or campaign-level product linkage details for videos in customized posts.
// Shop-level customized TikTok posts are generated by directly linking your TikTok videos to a product at the TikTok Shop level. If the linked product is part of an active campaign, the video linked to that product will be automatically added to that campaign. In contrast, campaign-level customized TikTok posts are generated by linking your TikTok videos to a product during the Product GMV Max Campaign creation process and are exclusive to the campaign.
func ShopVideoVideoAnchors(ctx context.Context, clt *core.SDKClient, req *gmvmax.ShopVideoVideoAnchorsRequest, accessToken string) ([]gmvmax.ShopVideoAnchor, error) {
	var resp gmvmax.ShopVideoVideoAnchorsResponse
	if err := clt.Post(ctx, "v1.3/gmv_max/creation/shop_video/video_anchors/", req, &resp, accessToken); err != nil {
		return nil, err
	}
	return resp.Data.VideoList, nil
}
